c:
	javac -classpath ${CLASSPATH}:${CS5800_HOME}/sort/count/java/counting_sort.jar RadixSort.java TestRadixSort.java

r:
	java -classpath ${CLASSPATH}:${CS5800_HOME}/sort/count/java/counting_sort.jar TestRadixSort
