c:
	javac -classpath ${CLASSPATH}:${CS5800_HOME}/data_structure/heap/java/heap.jar HeapSort.java TestHeapSort.java

r:
	java -classpath ${CLASSPATH}:${CS5800_HOME}/data_structure/heap/java/heap.jar TestHeapSort
